name: "jakan_phone_store"
version: "1.0.0"
config-version: 2

# must match the top key in profiles\profiles.yml
profile: "jakan_phone_store"

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"
packages-install-path: "dbt_packages"

models:
  jakan_phone_store:
    +materialized: view
