version: 2

models:
  - name: stg_kilimall_products
    columns:
      - name: product_title
        description: "The title of the product"
        data_tests:
          - not_null
      - name: listing_id
        description: "The unique identifier for the product listing"
        data_tests:
          - not_null
      - name: store_name
        data_tests:
          - not_null
          - accepted_values:
              values: ['jakan phone store']
  
  - name: stg_oraimo_products
    columns: 
      - name: web_scrap_ts
        data_tests:
          - not_null
      - name: product_title
        data_tests:
          - not_null
      - name: current_price
        data_tests:
          - not_null  
      - name: stock_status
        data_tests:
          - not_null
      - name: in_stock
        data_tests:
          - not_null
      - name: category
        data_tests:
          - not_null
        
      
      