jakan_phone_store:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: jakan-group     # ← replace
      dataset: jakan_phone_store             # ← replace (or keep)
      threads: 4
      location: europe-west1                     # ← replace with your region (e.g. US/EU)
      priority: interactive
      timeout_seconds: 300
